version: '3.8'
services:
  web:
    build:
      dockerfile: ./docker/django/Dockerfile
      context: .
      target: prod
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:db"
    env_file:
      - .env
  db:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env